import type { ReactNode } from 'react';
import { getCategoryProgress } from '@/lib/inspection/progress';
import CategoryProgressBadge from './CategoryProgressBadge';

export type CategoryField = { name: string; label: string; options?: readonly string[]; inputType?: 'number' | 'checkbox' };

export default function CategorySection({ title, fields, values, noteName, children }: { title: string; fields: readonly CategoryField[]; values: Record<string, unknown>; noteName: string; children?: ReactNode }) {
  const progress = getCategoryProgress(values, fields.map((field) => field.name));
  return <section className="category-section"><div className="category-header"><h2>{title}</h2><CategoryProgressBadge progress={progress} /></div><div className="category-content"><div className="category-fields">{fields.map((field) => { const value = values[field.name]; const isBoolean = field.inputType === 'checkbox'; return <div key={field.name} className={`field-row ${isBoolean || value !== '' && value !== null && value !== undefined ? 'is-set' : 'is-unset'}`}>{isBoolean ? <label className="boolean-control"><input aria-label={field.label} name={field.name} type="checkbox" defaultChecked={Boolean(value)} />{field.label}</label> : <><span>{field.label}</span>{field.options ? <select aria-label={field.label} name={field.name} defaultValue={String(value ?? '')}><option value="">Select</option>{field.options.map((option) => <option key={option}>{option}</option>)}</select> : <input aria-label={field.label} name={field.name} type={field.inputType ?? 'text'} defaultValue={String(value ?? '')} placeholder="Enter value" />}</>}</div>; })}</div><label className="mt-4">Notes<textarea name={noteName} defaultValue={String(values[noteName] ?? '')} rows={3} placeholder="Notes" /></label>{children}</div></section>;
}